### ISSUE TITLE
Warning when pip install PyPtt

### ISSUE THREAD

**Issue by smailzhu** [PttCodingMan/PyPtt#47]
`pip install PyPtt --upgrade`

> Collecting PyPtt
>   Using cached PyPtt-0.9.1.tar.gz (50 kB)
>   WARNING: Generating metadata for package PyPtt produced metadata for project name unknown. Fix your #egg=PyPtt fragments.
> ...
> Installing collected packages: unknown
>   Attempting uninstall: unknown
>     Found existing installation: UNKNOWN 0.9.1
>     Uninstalling UNKNOWN-0.9.1:
>       Successfully uninstalled UNKNOWN-0.9.1
>     Running setup.py install for unknown ... done
> Successfully installed unknown-0.9.1

**Comment by PttCodingMan** [comment]
Fixed, thank you.
