### ISSUE TITLE
crawl_board搜尋文章作者有Bug

### ISSUE THREAD

**Issue by eri820503** [PttCodingMan/PyPtt#51]
我參考以下這段時:
[當然我們也可以像 getPost 那樣加入搜尋條件來爬我們的結果](https://github.com/PttCodingMan/PyPtt/tree/master/doc)

使用PTT.data_type.post_search_type.AUTHOR搜尋作者時，
get_newest_index會先a該作者搜尋文章範圍，
crawl_board的start_index, end_index會變成該作者的文章範圍(如：該作者在某版發10篇文章，會搜尋該版第1~10篇文章)
造成搜尋錯誤

**Comment by PttCodingMan** [comment]
您好，如果您要爬該作者文章，這樣下條件取得文章範圍是沒有錯的喔。
請問是發生怎樣的錯誤呢？

**Comment by PttCodingMan** [comment]
是否是因為沒有把同樣的搜尋條件放進 crawl_board ?

**Comment by PttCodingMan** [comment]
如果還有問題，請把出問題的程式碼給我看一下喔 :D
