### ISSUE TITLE
get_newest_index 搜尋條件未符合之回傳值問題

### ISSUE THREAD

**Issue by anemology** [PttCodingMan/PyPtt#54]
例如在 `Steam` 版搜尋作者 `ggaass`，但因為該版沒有該作者的文章，會回傳該版 **最大文章編號**。

這個其實沒有問題，因為實際在 ptt 操作下，用 `a` 或 `/` 搜尋，若沒有符合的搜尋結果，畫面是不會動的。

但利用 `get_newest_index` 搜尋時，是否可以加入判斷，若搜尋結果的文章編號 == 該版的最新文章編號，則拋出 `exception` 或是 `index=0`。

**Comment by PttCodingMan** [comment]
好，沒問題感謝你的回報。

**Comment by PttCodingMan** [comment]
已經在 0.9.17 修正囉!

例外請參考文件
https://github.com/PttCodingMan/PyPtt/tree/master/doc#pttexceptionsnosearchresult

**Comment by anemology** [comment]
OK了~感謝您
