### ISSUE TITLE
ConnectError: 連線失敗

### ISSUE THREAD

**Issue by matcha576** [PttCodingMan/PyPtt#66]
您好，
我在嘗試登入連線時(使用登入範例程式碼)無法順利運作，並會顯示登入失敗。log檔如下:
ConnectError                              Traceback (most recent call last)
<ipython-input-16-55a9484751e9> in <module>
     14 
     15 try:
---> 16     ptt_bot.login(ptt_id, password)
     17 except PTT.exceptions.LoginError:
     18     ptt_bot.log('登入失敗')

~\anaconda3\lib\site-packages\PyPtt\PTT.py in login(self, ptt_id, password, kick_other_login)
    264 
    265         try:
--> 266             return self._login(
    267                 ptt_id,
    268                 password,

~\anaconda3\lib\site-packages\PyPtt\PTT.py in _login(self, ptt_id, password, kick_other_login)
    244             import _api_loginout
    245 
--> 246         return _api_loginout.login(
    247             self,
    248             ptt_id,

~\anaconda3\lib\site-packages\PyPtt\_api_loginout.py in login(api, ptt_id, password, kick_other_login)
    110     api.config.kick_other_login = kick_other_login
    111 
--> 112     api.connect_core.connect()
    113 
    114     log.show_value(

~\anaconda3\lib\site-packages\PyPtt\connect_core.py in connect(self)
    248 
    249         if not connect_success:
--> 250             raise exceptions.ConnectError(self.config)
    251 
    252     def send(

ConnectError: 連線失敗

**Comment by PttCodingMan** [comment]
我這邊運作正常，想請問一下幾個點

1. PyPtt 版本
2. 作業系統
3. 完整程式碼

```batch
Welcome to PyPtt v 0.9.36 test case
PyPtt v 0.9.36
Developed by CodingMan
[1029 15:07:18][資訊] 繁體中文語言模組 [初始化]
[1029 15:07:18][資訊] 連線主機 [批踢踢]
[1029 15:07:18][資訊] 連線核心 [初始化]
[1029 15:07:18][資訊] PyPtt v 0.9.36 [初始化]
[1029 15:07:18][資訊] 連線核心 [啟動]
[1029 15:07:18][資訊] 連線模式 [WebSocket]
[1029 15:07:18][資訊] 登入帳號 [x]
[1029 15:07:18][資訊] 批踢踢訊息 [登入中，請稍候]
[1029 15:07:19][資訊] 批踢踢訊息 [不剔除其他登入]
[1029 15:07:23][資訊] 批踢踢訊息 [請按任意鍵繼續]
[1029 15:07:23][資訊] 批踢踢訊息 [回到主選單]
[1029 15:07:23][資訊] 批踢踢訊息 [登入成功]
已註冊使用者
[1029 15:07:23][資訊] 開始登出
[1029 15:07:23][資訊] 批踢踢訊息 [登出成功]
[1029 15:07:23][資訊] 登出 [完成]
```

**Comment by matcha576** [comment]
您好，
我使用的PyPtt版本為最新版本(0.9.36)，在window 10上使用Anaconda的Spyder運行(Python3.8)。
完整程式碼即為說明文件中的程式碼:
import sys
from PyPtt import PTT

ptt_bot = PTT.API()
try:
    ptt_bot.login(ptt_id, password)
except PTT.exceptions.LoginError:
    ptt_bot.log('登入失敗')
    sys.exit()
except PTT.exceptions.WrongIDorPassword:
    ptt_bot.log('帳號密碼錯誤')
    sys.exit()
except PTT.exceptions.LoginTooOften:
    ptt_bot.log('請稍等一下再登入')
    sys.exit()
ptt_bot.log('登入成功')

if ptt_bot.unregistered_user:
    print('未註冊使用者')

    if ptt_bot.process_picks != 0:
        print(f'註冊單處理順位 {ptt_bot.process_picks}')

if ptt_bot.registered_user:
    print('已註冊使用者')

# call ptt_bot other api

ptt_bot.logout()

**Comment by PttCodingMan** [comment]
已經驗證以下環境
1. 原生 python 3.8
可正常登入
2. Anaconda python 3.8
連線失敗，目前遭遇問題皆與 Anacoda 有關
經以下兩點調整後已經連線成功

> 第一點 https://github.com/PttCodingMan/PyPtt/tree/master/doc#%E9%81%AD%E9%81%87-the-event-loop-is-already-running-%E9%8C%AF%E8%AA%A4

> 第二點 https://github.com/PttCodingMan/PyPtt/tree/master/doc#%E5%9C%A8-anaconda-%E4%B8%AD%E9%81%AD%E9%81%87-certificate-verify-failed

調整後可正常連線
![image](https://user-images.githubusercontent.com/59732316/97590458-99c1b900-1a39-11eb-82d0-52837ae2ce63.png)

**Comment by matcha576** [comment]
感謝你的協助!
