### ISSUE TITLE
請求客製化 websockets 帶的 user-agent

### ISSUE THREAD

**Issue by wens** [PttCodingMan/PyPtt#68]
目前 websockets 沒有特別指定 user-agent ，會變成用預設的，像是 "Python/3.7 websockets/8.1" 。
希望能稍微修改變成像是 "Python/3.7 websockets/8.1 PyPtt/0.9.36" 這樣。

**Comment by PttCodingMan** [comment]
好的呦，懂你的意思。

**Comment by PttCodingMan** [comment]
完成，請參考 a90e8bfa4a6e1bef714d4a68d45743bbcae0a868

**Comment by wens** [comment]
感謝。

我會建議你把它原本的 DEFAULT version string 放在前面，
或許對你 debug 使用者提供的 log 會有點幫助? 不過這完全看你。 :p

**Comment by PttCodingMan** [comment]
我印出來的結果是這樣
Python/3.7 websockets/8.1 PyPtt/0.9.37

這應該是符合本來的 DEFAULT version string 放在前面?

**Comment by wens** [comment]
有的。我漏看了 += ...
