### ISSUE TITLE
Python 3.9 uao 發生錯誤

### ISSUE THREAD

**Issue by PichuChen** [PttCodingMan/PyPtt#73]
在使用 Python 3.9 的時候似乎會因為字元編碼集的名稱問題導致錯誤，錯誤訊息為：
```
LookupError: unknown encoding: big5-uao
```

經測試將 connect_core.py 當中的 big5-uao 改為 big5uao (共兩處) 可以解決問題

另外和這個問題可能有關 https://github.com/eight04/pyUAO/pull/1

**Comment by Lafudoci** [comment]
我也是 python 3.9 遇到同樣問題，照 @PichuChen 的方法確實排除了問題

**Comment by PttCodingMan** [comment]
預計會在 0.9.41 修正

**Comment by PttCodingMan** [comment]
已經推上 PyPi 了，更新看看。
