### ISSUE TITLE
SingleLog 是否為必須的依賴？

### ISSUE THREAD

**Issue by yan12125** [PttCodingMan/PyPtt#79]
您好：

在 README 中提到[相依函式庫](https://github.com/PttCodingMan/PyPtt#相依函式庫)包含 SingleLog，但似乎程式碼中並未 import SingleLog？ https://github.com/PttCodingMan/PyPtt/search?q=SingleLog 是否能考慮將此項依賴移除？

謝謝！

**Comment by PttCodingMan** [comment]
好的，我會盡快移除

**Comment by PttCodingMan** [comment]
我想了想決定全面導入 SingleLog!!!

**Comment by yan12125** [comment]
好的沒問題。我會再更新 AUR 包 https://aur.archlinux.org/packages/python-pyptt/。
