### ISSUE TITLE
在抓我的最愛的時候，碰到分隔線就不繼續往下抓看板了

### ISSUE THREAD

**Issue by openopentw** [PttCodingMan/PyPtt#81]
如題，在抓我的最愛的時候，碰到分隔線就不繼續往下抓看板了。

例如我的最愛是這樣：
![圖片](https://user-images.githubusercontent.com/13679570/114830789-2f41e100-9dff-11eb-8387-83a6bc2c9660.png)

使用 get_favourite_board() 的話只會抓到這些：
```
b04902xxx
b98902HW
EE_Comment
----------
NTU
NTUcourse
----------
```
後面的 Master_D 跟 Graduate 都沒有抓到。

原因應該是因為這一行（[PyPtt/_api_get_favourite_board.py#L77](https://github.com/PttCodingMan/PyPtt/blob/master/PyPtt/_api_get_favourite_board.py#L77)）：
```python
if board in board_list:
    return favourite_board_list
```
因為分隔線重複出現了，但其實分隔線不是板名，所以不應該就這樣停下，我建議可以改成這樣：
```python
if board != '----------' and board in board_list:
    return favourite_board_list
```
我在本機實測這樣是可以抓完的。

**Comment by PttCodingMan** [comment]
Fixed at PyPtt-0.9.47.
