### ISSUE TITLE
ConnectError: 連線失敗

### ISSUE THREAD

**Issue by mnba147258** [PttCodingMan/PyPtt#85]
### 連線問題 ### 
您好，
我在嘗試登入連線時會顯示連線失敗，小弟我對寫程式還很新手，再麻煩大大幫忙解答，萬分感謝
PyPtt 版本 :0.9.49
作業系統:電腦window 10在google colab上運行Python 3.7.12
完整程式碼:
! pip install PyPtt 
! pip install nest_asyncio
! pip install PTTLibrary
from PyPtt import PTT
ptt_bot = PTT.API()
import nest_asyncio
nest_asyncio.apply()
from PTTLibrary import PTT
ID = '****'
Password = '****'
PTTBot = PTT.Library()
ErrCode = PTTBot.login(ID, Password)
程式錯誤碼:
Multiple exceptions: [Errno 111] Connect call failed ('140.112.172.1', 443), [Errno 111] Connect call failed ('140.112.172.11', 443), [Errno 111] Connect call failed ('140.112.172.5', 443), [Errno 111] Connect call failed ('140.112.172.4', 443), [Errno 111] Connect call failed ('140.112.172.3', 443), [Errno 111] Connect call failed ('140.112.172.2', 443)
[1122 00:34:43][資訊] 連線批踢踢 [失敗]
[1122 00:34:43][資訊] 準備重新連線批踢踢 [3]
[1122 00:34:44][資訊] 準備重新連線批踢踢 [2]
[1122 00:34:45][資訊] 準備重新連線批踢踢 [1]
ConnectError                              Traceback (most recent call last)
<ipython-input-10-b8fe11bde57d> in <module>()
      3 Password = '******'
      4 PTTBot = PTT.Library()
----> 5 ErrCode = PTTBot.login(ID, Password)

3 frames
/usr/local/lib/python3.7/dist-packages/PTTLibrary/connect_core.py in connect(self)
    267 
    268         if not connect_success:
--> 269             raise exceptions.ConnectError(self.config)
    270 
    271     def send(

ConnectError: 連線失敗

**Comment by PttCodingMan** [comment]
你好，PTT 已經都把雲端位置封鎖了喔！

**Comment by mnba147258** [comment]
在VS code就可以使用了，非常感謝

**Comment by PttCodingMan** [comment]
私下回覆過了，不過還是留個紀錄。

PTT 已經都把雲端相關的 ip 封鎖了，
所以使用線上服務是無法透過 PyPtt 連線的喔！
